version: '2'

services:

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:2022.9.6
    container_name: homeassistant
    ports:
      - "8123:8123"
    volumes:
      - /home/pirate/Projects/home-assistant-configuration:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always

